spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mpti?serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true




logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace